# @package _global_

dset:
  musdb: /user/b/bsteers/ccrma_upmix_fzs/mini_dataset # FZS
  use_musdb: false   # set to false to not use musdb as training data. FZS
  wav: /user/b/bsteers/ccrma_upmix_fzs/mini_dataset # path to custom wav dataset  FZS 
  samplerate: 48000
  # sources: ['drums', 'bass', 'other', 'vocals']
  sources: ['L', 'R', 'C', 'Ls', 'Rs'] # FZS

epochs: 300
batch_size: 4

weights: [1., 1., 1., 1., 1.]  # FZS  weights over each source for the training/valid loss.

augment:
  repitch:
    proba: 0
  remix:
    proba: 0
  scale:
    proba: 0
  flip: false

test:
  nonhq: /user/b/bsteers/ccrma_upmix_fzs/mini_dataset  # FZS path to non hq MusDB for evaluation
