# @package _global_

dset:
  use_musdb: false   # set to false to not use musdb as training data. FZS
  # wav: /Users/fzs/Documents/projects/CCRMA_upmixer/merged_dataset # path to custom wav dataset # FZS 
  wav: /user/b/bsteers/ccrma_upmix_fzs/merged_dataset # path to custom wav dataset # FZS 
  samplerate: 48000
  # sources: ['drums', 'bass', 'other', 'vocals']
  sources: ['L', 'R', 'C', 'Ls', 'Rs'] # FZS

epochs: 100
batch_size: 64